on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant-dir: ['base', 'standard']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ${{ matrix.variant-dir }}/package.json
          dry-run: true